[package]
name = "option-process-rust"
version = "0.1.0"
authors = ["x2h1z <zckuna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.13.0"
libm = "0.2.1"
mysql = "20.1.0"
serde_json = "1.0"